import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { Suspense } from "react";
import Loading from "../components/shared/loading/loading"
import Navbar from "@/components/shared/navbar/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ECOMMERCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Suspense fallback={<Loading/>} >
        <body className={inter.className}>
          <Navbar/>
          {children}
        </body>
        </Suspense>
    </html>
  );
}
